### ISSUE TITLE
full stop at the end of all entries?

### ISSUE THREAD

**Issue by Glottotopia** [langsci/74Brindle#11]
Should it be a full stop at the end of all entries? e.g. at the end of English definition, see tamaa?

**Comment by Glottotopia** [comment]
there is no entry tamaa

**Comment by Glottotopia** [comment]
"tamãã [tàmã́ã̀] n. hope." 
Is this correct like this?

**Comment by Glottotopia** [comment]
@jabrindle can we close this?

**Comment by jabrindle** [comment]
Yepp
