### ISSUE TITLE
missing 'second sense' in Reversal

### ISSUE THREAD

**Issue by jabrindle** [langsci/74Brindle#22]
no entry for English 'red', while 2 entries exist; sɪama and sɪarɪ, which suggest larger problem of senses to glosses, but 'ripe' is there, so it suggests only sense 2 is there, not sense 1 (see also ɛmbɛlɪ 'shoulder' not under shoulder in reversal index), generally two senses seems problematic (see bɔg), for same reason, see also the English 'leg' doesn't appear

**Comment by Glottotopia** [comment]
this is correct in my file. 
red sɪama<sub>1</sub> n.; sɪarɪ<sub>1</sub> v.

**Comment by jabrindle** [comment]
You rendering is good. Mine not. I think my project folder may not contain your changes.
