### ISSUE TITLE
material after material in italic is not appearing in Dictionary

### ISSUE THREAD

**Issue by jabrindle** [langsci/74Brindle#23]
material after material in italic is not appearing (see sɪŋbʊl)

**Comment by Glottotopia** [comment]
```
<LexSense_Definition>
    <AStr ws="en">
      <Run ws="en">remaining of </Run>
      <Run ws="cli" namedStyle="Emphasized Text">sɪŋtʃaara</Run>
      <Run ws="en">, after a night in its container, much sweeter than other </Run>
      <Run ws="en" namedStyle="Emphasized Text">pitos</Run>
    </AStr>
</LexSense_Definition>
```

becomes 

```
\newentry
\hypertarget{hvo4711}{}%
\headword{sɪŋbʊl}%
\hypertarget{hvo8459}{}%
\ipa{sɪ̀mbʊ́l}%
\typecf{\hyperlink{hvo34476}{sɪŋsɪama}; \hyperlink{hvo19296}{sɪŋhũor}; \hyperlink{hvo35550}{sɪŋtʃaara}}%
\synpos{n}%
\hypertarget{hvo632}{}%
\definition{remaining of \textsl{sɪŋtʃaara}, after a night in its container, much sweeter than other pitos}%
\lsgloss{pito (unfermented)}%
{\definitioncloser}
```

**Comment by Glottotopia** [comment]
I do not see any disappearing material here. But `<Run ws="en" namedStyle="Emphasized Text">pitos</Run>` does not show up as `\textsl`, as would be necessary

**Comment by Glottotopia** [comment]
The problem relates to emphasized text in  `<Run ws="en"...>`. It should work for emphasized text in  `<Run ws="cli"...>`.
- Is "pito" a Chakali word, an English word, or a word in some other language?
- Do we expect any other instances of non-Chakali emphasized words?

**Comment by jabrindle** [comment]
```
Is "pito" a Chakali word, an English word, or a word in some other language?
```

It is a Ghanaian English word. If possible, any Emphasized Text should be emphasized, but I expect only ws="en" and ws="cli" to be present.

```
Do we expect any other instances of non-Chakali emphasized words?
```

Simple search says 5 in current xml (<Run ws="en" namedStyle="Emphasized Text">), but one should be open to the possibility for both 'en' and 'cli' (not for this edition but for next or other similar projects)

**Comment by Glottotopia** [comment]
now everything which is either `ws="cli"` or `namedStyle="emphasizedText"` is in italics.
